services:
  semantic-engine:
    build: .
    container_name: trademarkia_service
    ports:
      - '8000:8000'
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
